---
- name: install httpd
  yum:
    name: httpd
    state: latest
- name: start httpd
  service:
    name: httpd
    state: started
    enabled: yes
- name: install git
  yum:
    name: git
    state: latest
- name: clone git
  git:
    repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
    dest: /var/www/html
    force: true
- name: set db server
  command: sed -i 's/172.20.1.101/{{ db_server_ip }}/g' /var/www/html/index.php

