---
- name: Install firewalld
  yum:
    name: firewalld
    state: latest
- name: Service firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
- name: firewall port
  firewalld:
    port: '{{ firewall_port }}'
    permanent: true
    zone: public
    immediate: true
    state: enabled

