---
- name: mariadb setting
  hosts: mariadb1
  become: true
  tasks:
    - include: tasks/deploy_db.yml   

- name: web server
  hosts: web_servers
  become: true
  tasks:
    - include: tasks/deploy_web.yml

