---
- name: install mariadb
  yum:
    name: mariadb-server
    state: latest
- name: start mariadb
  service:
    name: mariadb
    state: started
    enabled: yes

- name: install mysql-python
  yum:
    name:
      - python3-pip
      - MySQL-python

- name: create user
  mysql_user:
    name: '{{ db_user }}'
    password: '{{ db_user_password }}'
    state: present
    priv: '*.*:ALL'
    host: '%'
- name: create db
  mysql_db:
    name: '{{ db_name }}'
    state: present
- name: file copy
  copy:
    src: /home/ec2-user/seperate_roles/db-load-script.sql
    dest: /home/ec2-user/sql/db-load-script.sql

- name: query db
  mysql_db:
    name: ecomdb
    state: import
    target: /home/ec2-user/sql/db-load-script.sql
  ignore_errors: yes

