- name: install httpd
  yum:
    name: httpd
    state: latest
- name: install php
  yum:
    name: php
    state: latest
- name: install php-mysql
  yum:
    name: php-mysql
    state: latest
- name: install firewalld
  yum:
    name: firewalld
    state: latest
- name: start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
- name: firewall 80port
  firewalld:
    port: 80/tcp
    permanent: true
    zone: public
    immediate: true
    state: enabled
- name: start httpd
  service:
    name: httpd
    state: started
    enabled: yes
- name: install git
  yum:
    name: git
    state: latest
- name: clone git
  git:
    repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
    dest: /var/www/html
    force: true
- name: set db server
  command: sed -i 's/172.20.1.101/13.231.116.89/g' /var/www/html/index.php

