---
- name: mariadb setting
  hosts: mariadb1
  become: true
  roles:
    - mariadb_db
    - firewalld
  
- name: web server
  hosts: web_servers
  become: true
  roles:
    - apache_web
    - firewalld
    - php
     

